import { TriggerNode } from './TriggerNode';
import { ConditionNode } from './ConditionNode';
import { ActionNode } from './ActionNode';
import { CodeNode } from './CodeNode';

export { TriggerNode } from './TriggerNode';
export type { TriggerNodeData } from './TriggerNode';

export { ConditionNode } from './ConditionNode';
export type { ConditionNodeData } from './ConditionNode';

export { ActionNode } from './ActionNode';
export type { ActionNodeData } from './ActionNode';

export { CodeNode } from './CodeNode';
export type { CodeNodeData } from './CodeNode';

// Node type mapping for React Flow
export const nodeTypes = {
  trigger: TriggerNode,
  condition: ConditionNode,
  action: ActionNode,
  code: CodeNode,
};

// Available node definitions for the sidebar - Comprehensive n8n-like library
export const availableNodes = {
  // ==================== TRIGGERS ====================
  triggers: [
    {
      type: 'trigger',
      label: 'Webhook',
      icon: '🔗',
      triggerType: 'webhook',
      description: 'Start workflow from HTTP request',
      category: 'Core',
    },
    {
      type: 'trigger',
      label: 'Schedule',
      icon: '⏰',
      triggerType: 'schedule',
      description: 'Run on a schedule (cron)',
      category: 'Core',
    },
    {
      type: 'trigger',
      label: 'Manual',
      icon: '▶️',
      triggerType: 'manual',
      description: 'Manually trigger workflow',
      category: 'Core',
    },
    {
      type: 'trigger',
      label: 'Call Completed',
      icon: '📞',
      triggerType: 'call_completed',
      description: 'When a call ends successfully',
      category: 'Convis',
    },
    {
      type: 'trigger',
      label: 'Call Failed',
      icon: '❌',
      triggerType: 'call_failed',
      description: 'When a call fails to connect',
      category: 'Convis',
    },
    {
      type: 'trigger',
      label: 'Call No Answer',
      icon: '📵',
      triggerType: 'call_no_answer',
      description: 'When call is not answered',
      category: 'Convis',
    },
    {
      type: 'trigger',
      label: 'Voicemail',
      icon: '📬',
      triggerType: 'call_voicemail',
      description: 'When call goes to voicemail',
      category: 'Convis',
    },
    {
      type: 'trigger',
      label: 'Campaign Completed',
      icon: '📊',
      triggerType: 'campaign_completed',
      description: 'When a campaign finishes',
      category: 'Convis',
    },
    {
      type: 'trigger',
      label: 'Form Submission',
      icon: '📋',
      triggerType: 'form_submission',
      description: 'When a form is submitted',
      category: 'Core',
    },
    {
      type: 'trigger',
      label: 'Email Received',
      icon: '📥',
      triggerType: 'email_received',
      description: 'When email is received',
      category: 'Communication',
    },
    // AI Assistant Triggers
    {
      type: 'trigger',
      label: 'AI Assistant Started',
      icon: '🤖',
      triggerType: 'ai_agent_started',
      description: 'When AI agent starts a conversation',
      category: 'AI Assistant',
    },
    {
      type: 'trigger',
      label: 'AI Assistant Intent',
      icon: '🎯',
      triggerType: 'ai_agent_intent',
      description: 'When specific intent is detected',
      category: 'AI Assistant',
    },
    {
      type: 'trigger',
      label: 'AI Assistant Keyword',
      icon: '🔑',
      triggerType: 'ai_agent_keyword',
      description: 'When keyword is spoken',
      category: 'AI Assistant',
    },
    {
      type: 'trigger',
      label: 'AI Assistant Sentiment',
      icon: '😊',
      triggerType: 'ai_agent_sentiment',
      description: 'When sentiment changes (angry, happy)',
      category: 'AI Assistant',
    },
    {
      type: 'trigger',
      label: 'AI Assistant Escalation',
      icon: '🚨',
      triggerType: 'ai_agent_escalation',
      description: 'When caller requests human agent',
      category: 'AI Assistant',
    },
    {
      type: 'trigger',
      label: 'AI Assistant Data Collected',
      icon: '📋',
      triggerType: 'ai_agent_data_collected',
      description: 'When AI collects specific data',
      category: 'AI Assistant',
    },
  ],

  // ==================== AI AGENT ACTIONS ====================
  aiAgent: [
    {
      type: 'action',
      label: 'AI Assistant Respond',
      icon: '💬',
      actionType: 'ai_agent_respond',
      description: 'Make AI agent say something',
      category: 'AI Assistant',
    },
    {
      type: 'action',
      label: 'AI Assistant Transfer',
      icon: '📞',
      actionType: 'ai_agent_transfer',
      description: 'Transfer call to human/number',
      category: 'AI Assistant',
    },
    {
      type: 'action',
      label: 'AI Assistant Hold',
      icon: '⏸️',
      actionType: 'ai_agent_hold',
      description: 'Put caller on hold',
      category: 'AI Assistant',
    },
    {
      type: 'action',
      label: 'AI Assistant Hangup',
      icon: '📴',
      actionType: 'ai_agent_hangup',
      description: 'End the call',
      category: 'AI Assistant',
    },
    {
      type: 'action',
      label: 'AI Assistant Set Context',
      icon: '🧠',
      actionType: 'ai_agent_set_context',
      description: 'Update AI agent context/memory',
      category: 'AI Assistant',
    },
    {
      type: 'action',
      label: 'AI Assistant Play Audio',
      icon: '🔊',
      actionType: 'ai_agent_play_audio',
      description: 'Play audio file to caller',
      category: 'AI Assistant',
    },
    {
      type: 'action',
      label: 'AI Assistant Collect Input',
      icon: '⌨️',
      actionType: 'ai_agent_collect_input',
      description: 'Collect DTMF or voice input',
      category: 'AI Assistant',
    },
    {
      type: 'action',
      label: 'AI Assistant Change Voice',
      icon: '🎤',
      actionType: 'ai_agent_change_voice',
      description: 'Switch AI voice mid-call',
      category: 'AI Assistant',
    },
    {
      type: 'action',
      label: 'AI Assistant Send SMS',
      icon: '📱',
      actionType: 'ai_agent_send_sms',
      description: 'Send SMS during call',
      category: 'AI Assistant',
    },
    {
      type: 'action',
      label: 'AI Assistant Book Meeting',
      icon: '📅',
      actionType: 'ai_agent_book_meeting',
      description: 'Book calendar appointment',
      category: 'AI Assistant',
    },
    {
      type: 'action',
      label: 'AI Assistant Lookup CRM',
      icon: '🔍',
      actionType: 'ai_agent_lookup_crm',
      description: 'Look up caller in CRM',
      category: 'AI Assistant',
    },
    {
      type: 'action',
      label: 'AI Assistant Update CRM',
      icon: '📝',
      actionType: 'ai_agent_update_crm',
      description: 'Update CRM with call data',
      category: 'AI Assistant',
    },
    {
      type: 'action',
      label: 'AI Assistant Tag Call',
      icon: '🏷️',
      actionType: 'ai_agent_tag_call',
      description: 'Add tags to call record',
      category: 'AI Assistant',
    },
    {
      type: 'action',
      label: 'AI Assistant Set Priority',
      icon: '⭐',
      actionType: 'ai_agent_set_priority',
      description: 'Set call/lead priority',
      category: 'AI Assistant',
    },
    {
      type: 'action',
      label: 'AI Assistant Create Task',
      icon: '✅',
      actionType: 'ai_agent_create_task',
      description: 'Create follow-up task',
      category: 'AI Assistant',
    },
    {
      type: 'action',
      label: 'AI Assistant Webhook',
      icon: '🔗',
      actionType: 'ai_agent_webhook',
      description: 'Call external webhook mid-call',
      category: 'AI Assistant',
    },
  ],

  // ==================== CONDITIONS / FLOW ====================
  conditions: [
    {
      type: 'condition',
      label: 'IF',
      icon: '🔀',
      conditionType: 'if',
      description: 'Branch based on condition',
      category: 'Flow',
    },
    {
      type: 'condition',
      label: 'Switch',
      icon: '⚡',
      conditionType: 'switch',
      description: 'Multiple output branches',
      category: 'Flow',
    },
    {
      type: 'condition',
      label: 'Filter',
      icon: '🔍',
      conditionType: 'filter',
      description: 'Only continue if conditions match',
      category: 'Flow',
    },
    {
      type: 'condition',
      label: 'Validation',
      icon: '✓',
      conditionType: 'validation',
      description: 'Validate data format',
      category: 'Flow',
    },
    {
      type: 'condition',
      label: 'Dedup Check',
      icon: '🔄',
      conditionType: 'dedup',
      description: 'Check for duplicates',
      category: 'Flow',
    },
    {
      type: 'condition',
      label: 'Compare',
      icon: '⚖️',
      conditionType: 'compare',
      description: 'Compare two values',
      category: 'Flow',
    },
    {
      type: 'condition',
      label: 'Is Empty',
      icon: '❓',
      conditionType: 'is_empty',
      description: 'Check if value is empty',
      category: 'Flow',
    },
    {
      type: 'condition',
      label: 'Regex Match',
      icon: '🔤',
      conditionType: 'regex',
      description: 'Match against regex pattern',
      category: 'Flow',
    },
  ],

  // ==================== CODE / DATA TRANSFORMATION ====================
  code: [
    {
      type: 'code',
      label: 'Code',
      icon: '💻',
      codeType: 'custom',
      description: 'Write custom JavaScript',
      category: 'Core',
    },
    {
      type: 'code',
      label: 'Set',
      icon: '✏️',
      codeType: 'set',
      description: 'Set values in data',
      category: 'Data',
    },
    {
      type: 'code',
      label: 'Extract Fields',
      icon: '{ }',
      codeType: 'extract_fields',
      description: 'Extract data from input',
      category: 'Data',
    },
    {
      type: 'code',
      label: 'Rename Keys',
      icon: '🏷️',
      codeType: 'rename_keys',
      description: 'Rename object keys',
      category: 'Data',
    },
    {
      type: 'code',
      label: 'Merge',
      icon: '🔗',
      codeType: 'merge',
      description: 'Merge multiple inputs',
      category: 'Data',
    },
    {
      type: 'code',
      label: 'Split',
      icon: '✂️',
      codeType: 'split',
      description: 'Split data into batches',
      category: 'Data',
    },
    {
      type: 'code',
      label: 'Aggregate',
      icon: '📊',
      codeType: 'aggregate',
      description: 'Aggregate/summarize data',
      category: 'Data',
    },
    {
      type: 'code',
      label: 'Sort',
      icon: '↕️',
      codeType: 'sort',
      description: 'Sort array data',
      category: 'Data',
    },
    {
      type: 'code',
      label: 'Limit',
      icon: '🔢',
      codeType: 'limit',
      description: 'Limit number of items',
      category: 'Data',
    },
    {
      type: 'code',
      label: 'Remove Duplicates',
      icon: '🧹',
      codeType: 'remove_duplicates',
      description: 'Remove duplicate items',
      category: 'Data',
    },
    {
      type: 'code',
      label: 'Generate Key',
      icon: '🔑',
      codeType: 'generate_key',
      description: 'Generate unique identifier',
      category: 'Data',
    },
    {
      type: 'code',
      label: 'Increment',
      icon: '➕',
      codeType: 'increment',
      description: 'Increment a counter value',
      category: 'Data',
    },
    {
      type: 'code',
      label: 'Mark Processed',
      icon: '✅',
      codeType: 'mark_processed',
      description: 'Mark item as processed',
      category: 'Data',
    },
    {
      type: 'code',
      label: 'Date/Time',
      icon: '📅',
      codeType: 'datetime',
      description: 'Format/manipulate dates',
      category: 'Data',
    },
    {
      type: 'code',
      label: 'Math',
      icon: '🔢',
      codeType: 'math',
      description: 'Mathematical operations',
      category: 'Data',
    },
    {
      type: 'code',
      label: 'JSON Parse',
      icon: '{ }',
      codeType: 'json_parse',
      description: 'Parse JSON string',
      category: 'Data',
    },
    {
      type: 'code',
      label: 'JSON Stringify',
      icon: '📄',
      codeType: 'json_stringify',
      description: 'Convert to JSON string',
      category: 'Data',
    },
    {
      type: 'code',
      label: 'HTML Extract',
      icon: '🌐',
      codeType: 'html_extract',
      description: 'Extract data from HTML',
      category: 'Data',
    },
    {
      type: 'code',
      label: 'XML Parse',
      icon: '📑',
      codeType: 'xml_parse',
      description: 'Parse XML data',
      category: 'Data',
    },
    {
      type: 'code',
      label: 'Crypto',
      icon: '🔐',
      codeType: 'crypto',
      description: 'Hash/encrypt data',
      category: 'Data',
    },
  ],

  // ==================== ACTIONS - COMMUNICATION ====================
  communication: [
    {
      type: 'action',
      label: 'Send Email (SMTP)',
      icon: '📧',
      actionType: 'send_email',
      description: 'Send email via SMTP',
      category: 'Communication',
    },
    {
      type: 'action',
      label: 'Gmail',
      icon: '📧',
      actionType: 'gmail',
      description: 'Send via Gmail API',
      category: 'Communication',
    },
    {
      type: 'action',
      label: 'Outlook',
      icon: '📬',
      actionType: 'outlook',
      description: 'Send via Outlook/O365',
      category: 'Communication',
    },
    {
      type: 'action',
      label: 'SendGrid',
      icon: '📤',
      actionType: 'sendgrid',
      description: 'Send via SendGrid',
      category: 'Communication',
    },
    {
      type: 'action',
      label: 'Mailchimp',
      icon: '🐵',
      actionType: 'mailchimp',
      description: 'Mailchimp integration',
      category: 'Communication',
    },
    {
      type: 'action',
      label: 'Slack',
      icon: '💬',
      actionType: 'slack_message',
      description: 'Send message to Slack',
      category: 'Communication',
    },
    {
      type: 'action',
      label: 'Microsoft Teams',
      icon: '👥',
      actionType: 'teams_message',
      description: 'Send to MS Teams',
      category: 'Communication',
    },
    {
      type: 'action',
      label: 'Discord',
      icon: '🎮',
      actionType: 'discord',
      description: 'Send to Discord',
      category: 'Communication',
    },
    {
      type: 'action',
      label: 'Telegram',
      icon: '✈️',
      actionType: 'telegram',
      description: 'Send via Telegram',
      category: 'Communication',
    },
    {
      type: 'action',
      label: 'WhatsApp',
      icon: '📱',
      actionType: 'whatsapp',
      description: 'Send via WhatsApp',
      category: 'Communication',
    },
    {
      type: 'action',
      label: 'Twilio SMS',
      icon: '📲',
      actionType: 'twilio_sms',
      description: 'Send SMS via Twilio',
      category: 'Communication',
    },
    {
      type: 'action',
      label: 'Push Notification',
      icon: '🔔',
      actionType: 'push_notification',
      description: 'Send push notification',
      category: 'Communication',
    },
  ],

  // ==================== ACTIONS - CRM ====================
  crm: [
    {
      type: 'action',
      label: 'HubSpot Contact',
      icon: '🧡',
      actionType: 'hubspot_contact',
      description: 'Create/update HubSpot contact',
      category: 'CRM',
    },
    {
      type: 'action',
      label: 'HubSpot Deal',
      icon: '💰',
      actionType: 'hubspot_deal',
      description: 'Create/update HubSpot deal',
      category: 'CRM',
    },
    {
      type: 'action',
      label: 'HubSpot Note',
      icon: '📝',
      actionType: 'hubspot_note',
      description: 'Add note to HubSpot',
      category: 'CRM',
    },
    {
      type: 'action',
      label: 'Salesforce',
      icon: '☁️',
      actionType: 'salesforce',
      description: 'Salesforce operations',
      category: 'CRM',
    },
    {
      type: 'action',
      label: 'Pipedrive',
      icon: '📈',
      actionType: 'pipedrive',
      description: 'Pipedrive operations',
      category: 'CRM',
    },
    {
      type: 'action',
      label: 'Zoho CRM',
      icon: '📊',
      actionType: 'zoho_crm',
      description: 'Zoho CRM operations',
      category: 'CRM',
    },
    {
      type: 'action',
      label: 'Freshsales',
      icon: '🍃',
      actionType: 'freshsales',
      description: 'Freshsales operations',
      category: 'CRM',
    },
    {
      type: 'action',
      label: 'Close CRM',
      icon: '🎯',
      actionType: 'close_crm',
      description: 'Close.com operations',
      category: 'CRM',
    },
    {
      type: 'action',
      label: 'ActiveCampaign',
      icon: '📧',
      actionType: 'activecampaign',
      description: 'ActiveCampaign operations',
      category: 'CRM',
    },
    {
      type: 'action',
      label: 'Intercom',
      icon: '💬',
      actionType: 'intercom',
      description: 'Intercom operations',
      category: 'CRM',
    },
  ],

  // ==================== ACTIONS - PROJECT MANAGEMENT ====================
  projectManagement: [
    {
      type: 'action',
      label: 'Jira Create',
      icon: '🎫',
      actionType: 'create_jira',
      description: 'Create Jira ticket',
      category: 'Project Management',
    },
    {
      type: 'action',
      label: 'Jira Update',
      icon: '✏️',
      actionType: 'update_jira',
      description: 'Update Jira ticket',
      category: 'Project Management',
    },
    {
      type: 'action',
      label: 'Asana',
      icon: '📋',
      actionType: 'asana',
      description: 'Asana task operations',
      category: 'Project Management',
    },
    {
      type: 'action',
      label: 'Trello',
      icon: '📌',
      actionType: 'trello',
      description: 'Trello card operations',
      category: 'Project Management',
    },
    {
      type: 'action',
      label: 'Monday.com',
      icon: '📅',
      actionType: 'monday',
      description: 'Monday.com operations',
      category: 'Project Management',
    },
    {
      type: 'action',
      label: 'Notion',
      icon: '📓',
      actionType: 'notion',
      description: 'Notion page/database',
      category: 'Project Management',
    },
    {
      type: 'action',
      label: 'ClickUp',
      icon: '✅',
      actionType: 'clickup',
      description: 'ClickUp task operations',
      category: 'Project Management',
    },
    {
      type: 'action',
      label: 'Linear',
      icon: '📊',
      actionType: 'linear',
      description: 'Linear issue operations',
      category: 'Project Management',
    },
    {
      type: 'action',
      label: 'GitHub Issue',
      icon: '🐙',
      actionType: 'github_issue',
      description: 'Create/update GitHub issue',
      category: 'Project Management',
    },
    {
      type: 'action',
      label: 'GitLab Issue',
      icon: '🦊',
      actionType: 'gitlab_issue',
      description: 'Create/update GitLab issue',
      category: 'Project Management',
    },
    {
      type: 'action',
      label: 'Todoist',
      icon: '✅',
      actionType: 'todoist',
      description: 'Todoist task operations',
      category: 'Project Management',
    },
  ],

  // ==================== ACTIONS - DATABASES / STORAGE ====================
  databases: [
    {
      type: 'action',
      label: 'PostgreSQL',
      icon: '🐘',
      actionType: 'postgresql',
      description: 'PostgreSQL queries',
      category: 'Database',
    },
    {
      type: 'action',
      label: 'MySQL',
      icon: '🐬',
      actionType: 'mysql',
      description: 'MySQL queries',
      category: 'Database',
    },
    {
      type: 'action',
      label: 'MongoDB',
      icon: '🍃',
      actionType: 'mongodb',
      description: 'MongoDB operations',
      category: 'Database',
    },
    {
      type: 'action',
      label: 'Redis',
      icon: '🔴',
      actionType: 'redis',
      description: 'Redis operations',
      category: 'Database',
    },
    {
      type: 'action',
      label: 'Supabase',
      icon: '⚡',
      actionType: 'supabase',
      description: 'Supabase operations',
      category: 'Database',
    },
    {
      type: 'action',
      label: 'Firebase',
      icon: '🔥',
      actionType: 'firebase',
      description: 'Firebase/Firestore',
      category: 'Database',
    },
    {
      type: 'action',
      label: 'Airtable',
      icon: '📊',
      actionType: 'airtable',
      description: 'Airtable operations',
      category: 'Database',
    },
    {
      type: 'action',
      label: 'Google Sheets',
      icon: '📗',
      actionType: 'google_sheets',
      description: 'Google Sheets operations',
      category: 'Database',
    },
    {
      type: 'action',
      label: 'Excel (O365)',
      icon: '📊',
      actionType: 'excel',
      description: 'Excel Online operations',
      category: 'Database',
    },
    {
      type: 'action',
      label: 'Snowflake',
      icon: '❄️',
      actionType: 'snowflake',
      description: 'Snowflake queries',
      category: 'Database',
    },
    {
      type: 'action',
      label: 'BigQuery',
      icon: '📊',
      actionType: 'bigquery',
      description: 'BigQuery operations',
      category: 'Database',
    },
  ],

  // ==================== ACTIONS - FILES / STORAGE ====================
  files: [
    {
      type: 'action',
      label: 'Google Drive',
      icon: '📁',
      actionType: 'google_drive',
      description: 'Google Drive operations',
      category: 'Files',
    },
    {
      type: 'action',
      label: 'Dropbox',
      icon: '📦',
      actionType: 'dropbox',
      description: 'Dropbox operations',
      category: 'Files',
    },
    {
      type: 'action',
      label: 'OneDrive',
      icon: '☁️',
      actionType: 'onedrive',
      description: 'OneDrive operations',
      category: 'Files',
    },
    {
      type: 'action',
      label: 'AWS S3',
      icon: '🪣',
      actionType: 's3',
      description: 'AWS S3 operations',
      category: 'Files',
    },
    {
      type: 'action',
      label: 'FTP/SFTP',
      icon: '📂',
      actionType: 'ftp',
      description: 'FTP/SFTP operations',
      category: 'Files',
    },
    {
      type: 'action',
      label: 'Read/Write File',
      icon: '📄',
      actionType: 'file',
      description: 'Local file operations',
      category: 'Files',
    },
    {
      type: 'action',
      label: 'PDF',
      icon: '📕',
      actionType: 'pdf',
      description: 'PDF operations',
      category: 'Files',
    },
    {
      type: 'action',
      label: 'CSV',
      icon: '📋',
      actionType: 'csv',
      description: 'CSV read/write',
      category: 'Files',
    },
  ],

  // ==================== ACTIONS - HTTP / API ====================
  api: [
    {
      type: 'action',
      label: 'HTTP Request',
      icon: '🌐',
      actionType: 'http_request',
      description: 'Make HTTP/REST request',
      category: 'API',
    },
    {
      type: 'action',
      label: 'GraphQL',
      icon: '📊',
      actionType: 'graphql',
      description: 'GraphQL query/mutation',
      category: 'API',
    },
    {
      type: 'action',
      label: 'SOAP',
      icon: '🧼',
      actionType: 'soap',
      description: 'SOAP API request',
      category: 'API',
    },
    {
      type: 'action',
      label: 'Webhook Response',
      icon: '↩️',
      actionType: 'webhook_response',
      description: 'Respond to webhook',
      category: 'API',
    },
  ],

  // ==================== ACTIONS - AI / ML ====================
  ai: [
    {
      type: 'action',
      label: 'OpenAI',
      icon: '🤖',
      actionType: 'openai',
      description: 'GPT/ChatGPT operations',
      category: 'AI',
    },
    {
      type: 'action',
      label: 'Claude (Anthropic)',
      icon: '🧠',
      actionType: 'anthropic',
      description: 'Claude AI operations',
      category: 'AI',
    },
    {
      type: 'action',
      label: 'Text Classification',
      icon: '🏷️',
      actionType: 'text_classification',
      description: 'Classify text content',
      category: 'AI',
    },
    {
      type: 'action',
      label: 'Sentiment Analysis',
      icon: '😊',
      actionType: 'sentiment',
      description: 'Analyze sentiment',
      category: 'AI',
    },
    {
      type: 'action',
      label: 'Summarize',
      icon: '📝',
      actionType: 'summarize',
      description: 'Summarize text',
      category: 'AI',
    },
    {
      type: 'action',
      label: 'Translate',
      icon: '🌍',
      actionType: 'translate',
      description: 'Translate text',
      category: 'AI',
    },
    {
      type: 'action',
      label: 'Extract Entities',
      icon: '🔍',
      actionType: 'extract_entities',
      description: 'Extract named entities',
      category: 'AI',
    },
  ],

  // ==================== FLOW CONTROL ====================
  flowControl: [
    {
      type: 'action',
      label: 'Delay',
      icon: '⏱️',
      actionType: 'delay',
      description: 'Wait before continuing',
      category: 'Flow',
    },
    {
      type: 'action',
      label: 'Wait',
      icon: '⏳',
      actionType: 'wait',
      description: 'Wait for condition',
      category: 'Flow',
    },
    {
      type: 'action',
      label: 'Loop',
      icon: '🔁',
      actionType: 'loop',
      description: 'Loop over items',
      category: 'Flow',
    },
    {
      type: 'action',
      label: 'Split in Batches',
      icon: '📦',
      actionType: 'split_batches',
      description: 'Process in batches',
      category: 'Flow',
    },
    {
      type: 'action',
      label: 'Execute Workflow',
      icon: '▶️',
      actionType: 'execute_workflow',
      description: 'Run another workflow',
      category: 'Flow',
    },
    {
      type: 'action',
      label: 'Stop & Error',
      icon: '🛑',
      actionType: 'stop_error',
      description: 'Stop with error',
      category: 'Flow',
    },
    {
      type: 'action',
      label: 'No Operation',
      icon: '⏸️',
      actionType: 'noop',
      description: 'Do nothing (passthrough)',
      category: 'Flow',
    },
  ],

  // ==================== RESPONSES ====================
  responses: [
    {
      type: 'action',
      label: 'Respond OK',
      icon: '✅',
      actionType: 'respond',
      description: 'End workflow with success',
      config: { responseType: 'ok' },
    },
    {
      type: 'action',
      label: 'Respond Ignored',
      icon: '⏭️',
      actionType: 'respond',
      description: 'End workflow - ignored',
      config: { responseType: 'ignored' },
    },
    {
      type: 'action',
      label: 'Respond Failed',
      icon: '❌',
      actionType: 'respond',
      description: 'End workflow with failure',
      config: { responseType: 'failed' },
    },
    {
      type: 'action',
      label: 'Respond Duplicate',
      icon: '🔄',
      actionType: 'respond',
      description: 'End workflow - duplicate',
      config: { responseType: 'duplicate' },
    },
  ],

  // ==================== DEVELOPER / UTILITY ====================
  utility: [
    {
      type: 'action',
      label: 'Execute Command',
      icon: '💻',
      actionType: 'execute_command',
      description: 'Run shell command',
      category: 'Developer',
    },
    {
      type: 'action',
      label: 'SSH',
      icon: '🔐',
      actionType: 'ssh',
      description: 'SSH command execution',
      category: 'Developer',
    },
    {
      type: 'code',
      label: 'Function',
      icon: 'ƒ',
      codeType: 'function',
      description: 'Custom JavaScript function',
      category: 'Developer',
    },
    {
      type: 'action',
      label: 'Debug',
      icon: '🐛',
      actionType: 'debug',
      description: 'Log debug information',
      category: 'Developer',
    },
    {
      type: 'action',
      label: 'Error Trigger',
      icon: '⚠️',
      actionType: 'error_trigger',
      description: 'Handle errors',
      category: 'Developer',
    },
  ],

  // ==================== E-COMMERCE ====================
  ecommerce: [
    {
      type: 'action',
      label: 'Shopify',
      icon: '🛒',
      actionType: 'shopify',
      description: 'Shopify operations',
      category: 'E-commerce',
    },
    {
      type: 'action',
      label: 'WooCommerce',
      icon: '🛍️',
      actionType: 'woocommerce',
      description: 'WooCommerce operations',
      category: 'E-commerce',
    },
    {
      type: 'action',
      label: 'Stripe',
      icon: '💳',
      actionType: 'stripe',
      description: 'Stripe payments',
      category: 'E-commerce',
    },
    {
      type: 'action',
      label: 'PayPal',
      icon: '💰',
      actionType: 'paypal',
      description: 'PayPal operations',
      category: 'E-commerce',
    },
  ],

  // ==================== MARKETING ====================
  marketing: [
    {
      type: 'action',
      label: 'Google Ads',
      icon: '📢',
      actionType: 'google_ads',
      description: 'Google Ads operations',
      category: 'Marketing',
    },
    {
      type: 'action',
      label: 'Facebook Ads',
      icon: '📘',
      actionType: 'facebook_ads',
      description: 'Facebook Ads operations',
      category: 'Marketing',
    },
    {
      type: 'action',
      label: 'LinkedIn',
      icon: '💼',
      actionType: 'linkedin',
      description: 'LinkedIn operations',
      category: 'Marketing',
    },
    {
      type: 'action',
      label: 'Twitter/X',
      icon: '🐦',
      actionType: 'twitter',
      description: 'Twitter operations',
      category: 'Marketing',
    },
    {
      type: 'action',
      label: 'Google Analytics',
      icon: '📊',
      actionType: 'google_analytics',
      description: 'GA4 operations',
      category: 'Marketing',
    },
    {
      type: 'action',
      label: 'Segment',
      icon: '📈',
      actionType: 'segment',
      description: 'Segment analytics',
      category: 'Marketing',
    },
    {
      type: 'action',
      label: 'Mixpanel',
      icon: '📉',
      actionType: 'mixpanel',
      description: 'Mixpanel analytics',
      category: 'Marketing',
    },
  ],

  // ==================== CALENDAR / SCHEDULING ====================
  calendar: [
    {
      type: 'action',
      label: 'Google Calendar',
      icon: '📅',
      actionType: 'google_calendar',
      description: 'Google Calendar events',
      category: 'Calendar',
    },
    {
      type: 'action',
      label: 'Outlook Calendar',
      icon: '📆',
      actionType: 'outlook_calendar',
      description: 'Outlook calendar events',
      category: 'Calendar',
    },
    {
      type: 'action',
      label: 'Calendly',
      icon: '🗓️',
      actionType: 'calendly',
      description: 'Calendly operations',
      category: 'Calendar',
    },
    {
      type: 'action',
      label: 'Cal.com',
      icon: '📅',
      actionType: 'calcom',
      description: 'Cal.com operations',
      category: 'Calendar',
    },
  ],
};

// Helper to get all nodes as flat array
export const getAllNodes = () => {
  return Object.values(availableNodes).flat();
};

// Helper to get nodes by category
export const getNodesByCategory = (category: string) => {
  return getAllNodes().filter((node: any) => node.category === category);
};

// Get unique categories
export const getCategories = () => {
  const categories = new Set<string>();
  getAllNodes().forEach((node: any) => {
    if (node.category) {
      categories.add(node.category);
    }
  });
  return Array.from(categories);
};
